### ISSUE TITLE
 Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by baelter** [npolar/npdc-gulp#3]
```
 Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/home/anders/Projects/npdc/npdc-gulp/node_modules/browser-sync/node_modules/serve-static/node_modules/send/index.js:326:13)
    at SendStream.send (/home/anders/Projects/npdc/npdc-gulp/node_modules/browser-sync/node_modules/serve-static/node_modules/send/index.js:525:17)
    at /home/anders/Projects/npdc/npdc-gulp/node_modules/browser-sync/node_modules/serve-static/node_modules/send/index.js:669:12
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by baelter** [comment]
Happens on search
